name: Matrixのテスト

on:
  workflow_dispatch:

jobs:
  matrix-test:
    name: Matrixのテスト
    runs-on: ubuntu-latest
    strategy:
      matrix:
          environment: [test, staging, production]
    steps:
      - name: Matrixのテスト
        run: echo ${{ matrix.environment }}
